### ISSUE TITLE
error when run sdcadm post-setup cmon

### ISSUE THREAD

**Issue by tangfeng123** [joyent/triton-cmon#1]
...alling cmon-agent [=======================>] 100%        6                  
"cmon-agent" install failed on 6 servers.
sdcadm post-setup cmon: error (MultiError): multiple (6) errors
    error (Update): Task ccef73cd-7d04-41cb-b04a-1e8c780aa3da failed with error: AgentInstall error: Command failed: cp: cannot access /opt/smartdc/agents/lib/node_modules/cmon-agent

    error (Update): Task 5fd8b0b4-4fbf-40f6-80d9-d2ed2b472c09 failed with error: AgentInstall error: Command failed: cp: cannot access /opt/smartdc/agents/lib/node_modules/cmon-agent

    error (Update): Task 7faa5476-b823-4aa2-a506-e7b2228a0b0b failed with error: AgentInstall error: Command failed: cp: cannot access /opt/smartdc/agents/lib/node_modules/cmon-agent

    error (Update): Task 4fd97a44-9d43-4600-bb85-7da5fda5b462 failed with error: AgentInstall error: Command failed: cp: cannot access /opt/smartdc/agents/lib/node_modules/cmon-agent

    error (Update): Task e16e0108-a27a-4ee6-b2b3-aa2ae42c5ade failed with error: AgentInstall error: Command failed: cp: cannot access /opt/smartdc/agents/lib/node_modules/cmon-agent

    error (Update): Task 3ecc6ec3-2ae7-4dd8-b1a3-976671efb3aa failed with error: AgentInstall error: Command failed: cp: cannot access /opt/smartdc/agents/lib/node_modules/cmon-agent

How can I reslove this

**Comment by richardkiene** [comment]
Hi @tangfeng123,

Thanks for reporting this. Your issue actually looks like something is wrong with [sdcadm](https://github.com/joyent/sdcadm) not cmon or cmon-agent. Would you mind opening up an issue on [sdcadm](https://github.com/joyent/sdcadm) and reaching out to one of us in [IRC](https://wiki.smartos.org/display/DOC/Mailing+Lists+and+IRC)?

If you could also include the output from `sdcadm -v post-setup cmon 2>&1 | tee post-setup-cmon.log` when you open up the sdcadm issue that would be helpful.
