### ISSUE TITLE
There have something wrong for test

### ISSUE THREAD

**Issue by tangfeng123** [joyent/triton-cmon#2]
I have deploy the cmon and cmon-agent in my env. and use the command line curl could dsicover and get the instance's informaiton.

but when I run below test
root@6b3fdb33-0149-446e-c6bf-84d42fb1bde4:~/.ssh# curl --insecure --cert-type pem --cert promcert.pem --key promkey.pem "https://3918d5cd-99c1-4ce1-bfe2-07fbd38fa3d3.cmon.bst-1.bstjpc.com:9163/metrics"

curl: (6) Could not resolve host: 3918d5cd-99c1-4ce1-bfe2-07fbd38fa3d3.cmon.bst-1.bstjpc.com

it is notice me above error infomation, seems vmapi or cns is not working smooth.

And When I create a new container finished, There is no CNAME record created.
So in my promethues system, all the instance show down like below.
Get https://500250f3-833b-470f-ad2d-10c6464a7e8f.cmon.bst-1.bstjpc.com:9163/metrics: dial tcp: lookup 500250f3-833b-470f-ad2d-10c6464a7e8f.cmon.bst-1.bstjpc.com on 203.241.132.34:53: no such host

is it cause by the vmapi version too low?
this is my vmapi version
release-20161027-20161027T010017Z-gaf77e72

any comment is appreciate.

**Comment by richardkiene** [comment]
Hi @tangfeng123,

Thanks for the report! CMON doesn't actually create or remove the DNS records used for retrieving metrics, so it would seem that this issue probably doesn't have anything to do with CMON. It appears you're already interacting with @arekinath in https://github.com/joyent/triton-cns/issues/5 which is probably the more appropriate area for this. I'm going to close this out for now.
