### ISSUE TITLE
how to specify network instead of external when installing triton-cmon

### ISSUE THREAD

**Issue by bruceyang15** [joyent/triton-cmon#4]
I am trying to setup cmon on my headnode, and got the following error message.

sdcadm post-setup cmon: error (SDCClient): sapi client error (ProvisionFailedError): no more free IPs.

seems it will create 2 NICs with admin and external networks.
but my external networks contains public IP addresses and it runs out of IP.

is it possible to specify another network (private subnet) when I run "sdcadm post-setup cmon"?

thanks.

**Comment by bahamat** [comment]
At current, you can't. All of Triton's core stack components expect to be able to use the network named `external` wherever external interfaces are required, and it's a best practice to reserve that network for the `admin` user and provide other networks for tenant use.
