### ISSUE TITLE
Removed intances don't disappear from CMON automatically

### ISSUE THREAD

**Issue by jussisallinen** [joyent/triton-cmon#6]
There seems to be bug in triton-cmon (release-20170928​) which causes removed instances to stay in cmon as 'DOWN' until cmon service is manually restarted in cmon0 with svcadm restart cmon.

Is there already bugview or Gerrit page for tracking this?

**Comment by richardkiene** [comment]
Thanks for bringing this to our attention @jussisallinen. I've created a ticket for this and you can follow along with [CMON-87](https://smartos.org/bugview/CMON-87).

**Comment by joshwilsdon** [comment]
Fixed in 9a876baaeeaac56587a96b8fa912d98b69c80b7f
