### ISSUE TITLE
Get GZ metrics

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/triton-cmon#7]
Currently, all the examples in the documentation illustrate fetching the zone metrics.
The CMON agent, however, contains a `/v1/gz/metrics' endpoint.

Could you please provide some Prometheus configuration samples for the GZ metrics?

**Comment by richardkiene** [comment]
@benjamin-bergia I have yet to write the update to the TritonSD in Prometheus. I hope to get that done in the near future.

**Comment by benjamin-bergia** [comment]
@richardkiene thank you. In that case, I will close this.

**Comment by Smithx10** [comment]
@benjamin-bergia  

I just added this for my own use,  I don't know if it will be upstreamed,  but it works.

https://github.com/prometheus/prometheus/compare/master...Smithx10:triton_gz
